#!/usr/bin/env node
// archmap to-mermaid.mjs — рендер architecture.json → Mermaid (.mmd).
// Использование:
//   node to-mermaid.mjs --in <architecture.json> --out <architecture.mmd> [--view overview|data|api|modules|all]
// --view all пишет overview в --out и рядом architecture.data.mmd / architecture.api.mmd / architecture.modules.mmd.
// Экспортирует buildOverview/buildErd/buildApi/buildModules — to-md.mjs импортирует их, не копируя.

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { LAYERS, parseArgs, readJson } from './lib/core.mjs'

export const MMD_HEADER = '%% generated by archmap from architecture.json — do not edit'

const OVERVIEW_CAP = 80
// Зарезервированные слова Mermaid — такими id узлы называться не могут
const RESERVED_IDS = new Set(['end', 'class', 'click', 'subgraph', 'style', 'classdef', 'direction', 'linkstyle'])

export function sanitizeId(raw) {
  let id = String(raw).replace(/[^A-Za-z0-9_]/g, '_')
  if (/^\d/.test(id)) id = `n_${id}`
  if (!id) id = 'n_'
  if (RESERVED_IDS.has(id.toLowerCase())) id = `${id}_`
  return id
}

// Санация с гарантией уникальности: разные исходные id никогда не схлопываются в один
function idMapper() {
  const byRaw = new Map()
  const used = new Set()
  return (raw) => {
    if (byRaw.has(raw)) return byRaw.get(raw)
    let id = sanitizeId(raw)
    while (used.has(id)) id = `${id}_`
    used.add(id)
    byRaw.set(raw, id)
    return id
  }
}

export function quoteLabel(text) {
  const escaped = String(text)
    .replace(/&/g, '#amp;')
    .replace(/"/g, '#quot;')
    .replace(/</g, '#lt;')
    .replace(/>/g, '#gt;')
    .replace(/\s+/g, ' ')
    .trim()
  return `"${escaped}"`
}

function nodeLabel(node) {
  if (node.kind === 'route' && node.meta?.method) return `${node.meta.method} ${node.meta.path ?? node.label}`
  return node.label
}

// Форма узла по kind: table/store — цилиндр, agent — круг, env — флажок,
// svc/tech — стадион, component/llm-call — скруглённый, остальное — прямоугольник
function shape(node, mapId) {
  const id = mapId(node.id)
  const label = quoteLabel(nodeLabel(node))
  switch (node.kind) {
    case 'table':
    case 'store':
    case 'memory':
      return `${id}[(${label})]`
    case 'agent':
      return `${id}((${label}))`
    case 'env':
      return `${id}>${label}]`
    case 'external-service':
    case 'tech':
      return `${id}([${label}])`
    case 'component':
    case 'llm-call':
      return `${id}(${label})`
    default:
      return `${id}[${label}]`
  }
}

function edgeLine(edge, mapId) {
  const arrow = edge.inferred ? '-.->' : '-->'
  return `  ${mapId(edge.from)} ${arrow}|${quoteLabel(edge.kind)}| ${mapId(edge.to)}`
}

function byId(a, b) {
  return a.id.localeCompare(b.id)
}

function modulePath(node) {
  if (node.id.startsWith('module:')) return node.id.slice('module:'.length)
  return node.source?.file || node.label
}

// module-узлы → узлы-директории dir:<dirname> с label «dirname/ (N)»
function aggregateModules(nodes, edges) {
  const dirIdByModule = new Map()
  const dirs = new Map()
  for (const node of nodes) {
    if (node.layer !== 'logic' || node.kind !== 'module') continue
    const dir = path.posix.dirname(modulePath(node))
    const dirId = `dir:${dir}`
    dirIdByModule.set(node.id, dirId)
    if (!dirs.has(dirId)) dirs.set(dirId, { dir, count: 0, source: node.source })
    dirs.get(dirId).count++
  }
  if (!dirIdByModule.size) return { nodes, edges, aggregated: false, dirCount: 0 }
  const nextNodes = nodes.filter((node) => !dirIdByModule.has(node.id))
  for (const [dirId, info] of [...dirs.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    nextNodes.push({
      id: dirId, kind: 'module', layer: 'logic',
      label: `${info.dir}/ (${info.count})`,
      source: info.source, inferred: false, meta: { count: info.count },
    })
  }
  const seen = new Set()
  const nextEdges = []
  for (const edge of edges) {
    const from = dirIdByModule.get(edge.from) ?? edge.from
    const to = dirIdByModule.get(edge.to) ?? edge.to
    if (from === to) continue
    const key = `${edge.kind}:${from}->${to}`
    if (seen.has(key)) continue
    seen.add(key)
    nextEdges.push({ ...edge, from, to })
  }
  return { nodes: nextNodes, edges: nextEdges, aggregated: true, dirCount: dirs.size }
}

// CAP overview: сперва агрегация модулей, затем срез слоёв по приоритету data>api>agents>infra>client
function applyCap(nodes, edges) {
  const notes = []
  let list = [...nodes].sort(byId)
  let rest = [...edges].sort(byId)
  if (list.length > OVERVIEW_CAP) {
    const agg = aggregateModules(list, rest)
    if (agg.aggregated) {
      list = agg.nodes.sort(byId)
      rest = agg.edges.sort(byId)
      notes.push(`%% truncated: module nodes aggregated into ${agg.dirCount} directories (cap ${OVERVIEW_CAP})`)
    }
  }
  if (list.length > OVERVIEW_CAP) {
    const dropOrder = ['client', 'infra', 'agents', 'api', 'data', 'logic']
    for (const layerId of dropOrder) {
      if (list.length <= OVERVIEW_CAP) break
      const inLayer = list.filter((node) => node.layer === layerId)
      if (!inLayer.length) continue
      const excess = Math.min(list.length - OVERVIEW_CAP, inLayer.length)
      const drop = new Set(inLayer.slice(inLayer.length - excess).map((node) => node.id))
      list = list.filter((node) => !drop.has(node.id))
      notes.push(`%% truncated: ${excess} ${layerId} nodes dropped (cap ${OVERVIEW_CAP})`)
    }
  }
  const ids = new Set(list.map((node) => node.id))
  rest = rest.filter((edge) => ids.has(edge.from) && ids.has(edge.to))
  return { nodes: list, edges: rest, notes }
}

export function buildOverview(data) {
  const capped = applyCap(data.nodes, data.edges)
  const mapId = idMapper()
  const lines = [MMD_HEADER, ...capped.notes, 'flowchart LR']
  for (const layer of data.layers ?? LAYERS) {
    const inLayer = capped.nodes.filter((node) => node.layer === layer.id)
    if (!inLayer.length) continue
    lines.push(`  subgraph layer_${layer.id}[${quoteLabel(layer.label)}]`)
    for (const node of inLayer) lines.push(`    ${shape(node, mapId)}`)
    lines.push('  end')
  }
  for (const edge of capped.edges) lines.push(edgeLine(edge, mapId))
  for (const node of capped.nodes) {
    if (node.inferred) lines.push(`  style ${mapId(node.id)} stroke-dasharray: 5 5`)
  }
  return lines.join('\n') + '\n'
}

const ER_CARDINALITY = { '1:1': ['||', '||'], '1:N': ['||', 'o{'], 'N:1': ['}o', '||'], 'N:M': ['}o', 'o{'] }

export function buildErd(data) {
  const tables = data.nodes.filter((node) => node.kind === 'table').sort(byId)
  const mapId = idMapper()
  const lines = [MMD_HEADER, 'erDiagram']
  const tableIds = new Map()
  for (const table of tables) {
    const entity = mapId(table.label)
    tableIds.set(table.id, entity)
    lines.push(`  ${entity} {`)
    for (const column of table.meta?.columns ?? []) {
      const keys = []
      if (column.pk) keys.push('PK')
      if (column.fk) keys.push('FK')
      if (column.unique) keys.push('UK')
      const parts = [sanitizeId(column.type ?? 'unknown'), sanitizeId(column.name)]
      if (keys.length) parts.push(keys.join(', '))
      if (column.nullable) parts.push('"nullable"')
      lines.push(`    ${parts.join(' ')}`)
    }
    lines.push('  }')
  }
  const fkEdges = data.edges
    .filter((edge) => edge.kind === 'fk' && tableIds.has(edge.from) && tableIds.has(edge.to))
    .sort(byId)
  for (const edge of fkEdges) {
    const [left, right] = ER_CARDINALITY[edge.meta?.cardinality] ?? ER_CARDINALITY['N:1']
    // inferred → неидентифицирующая (пунктирная) связь
    const line = edge.inferred ? '..' : '--'
    const fromTable = data.nodes.find((node) => node.id === edge.from)
    const fkColumn = (fromTable?.meta?.columns ?? []).find((column) => column.fk?.table && edge.to.endsWith(`:${column.fk.table}`))
    const label = edge.label ?? fkColumn?.name ?? edge.meta?.through ?? 'fk'
    lines.push(`  ${tableIds.get(edge.from)} ${left}${line}${right} ${tableIds.get(edge.to)} : ${quoteLabel(label)}`)
  }
  return lines.join('\n') + '\n'
}

export function buildApi(data) {
  const mapId = idMapper()
  const nodeById = new Map(data.nodes.map((node) => [node.id, node]))
  const picked = new Map()
  const edges = []
  const sortedEdges = [...data.edges].sort(byId)
  for (const node of [...data.nodes].sort(byId)) {
    if (node.layer === 'api') picked.set(node.id, node)
  }
  // route → handles → module
  for (const edge of sortedEdges) {
    if (edge.kind !== 'handles' || !picked.has(edge.from)) continue
    const target = nodeById.get(edge.to)
    if (!target) continue
    picked.set(target.id, target)
    edges.push(edge)
  }
  // module → uses → table/store/svc
  for (const edge of sortedEdges) {
    if (edge.kind !== 'uses' || !picked.has(edge.from)) continue
    const target = nodeById.get(edge.to)
    if (!target || !['table', 'store', 'external-service'].includes(target.kind)) continue
    picked.set(target.id, target)
    edges.push(edge)
  }
  // middleware → guards → route
  for (const edge of sortedEdges) {
    if (edge.kind === 'guards' && picked.has(edge.from) && picked.has(edge.to)) edges.push(edge)
  }
  const lines = [MMD_HEADER, 'flowchart LR']
  for (const node of [...picked.values()].sort(byId)) lines.push(`  ${shape(node, mapId)}`)
  for (const edge of edges.sort(byId)) lines.push(edgeLine(edge, mapId))
  for (const node of [...picked.values()].sort(byId)) {
    if (node.inferred) lines.push(`  style ${mapId(node.id)} stroke-dasharray: 5 5`)
  }
  return lines.join('\n') + '\n'
}

export function buildModules(data) {
  const mapId = idMapper()
  const modules = data.nodes.filter((node) => node.layer === 'logic').sort(byId)
  const moduleIds = new Set(modules.map((node) => node.id))
  const groups = new Map()
  for (const node of modules) {
    const file = modulePath(node)
    const top = file.includes('/') ? file.split('/')[0] : '(root)'
    if (!groups.has(top)) groups.set(top, [])
    groups.get(top).push(node)
  }
  const lines = [MMD_HEADER, 'flowchart TD']
  for (const [top, members] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  subgraph dir_${sanitizeId(top)}[${quoteLabel(`${top}/`)}]`)
    for (const node of members) lines.push(`    ${shape(node, mapId)}`)
    lines.push('  end')
  }
  const moduleEdges = data.edges
    .filter((edge) => ['import', 'depends'].includes(edge.kind) && moduleIds.has(edge.from) && moduleIds.has(edge.to))
    .sort(byId)
  for (const edge of moduleEdges) lines.push(edgeLine(edge, mapId))
  for (const node of modules) {
    if (node.meta?.cycle) lines.push(`  style ${mapId(node.id)} stroke:#f87171,stroke-width:2px`)
    else if (node.inferred) lines.push(`  style ${mapId(node.id)} stroke-dasharray: 5 5`)
  }
  return lines.join('\n') + '\n'
}

const VIEWS = { overview: buildOverview, data: buildErd, api: buildApi, modules: buildModules }

function main() {
  const args = parseArgs(process.argv.slice(2), {
    in: { flag: '--in', default: null },
    out: { flag: '--out', default: null },
    view: { flag: '--view', default: 'overview' },
  })
  if (args.help || !args.in || !args.out) {
    console.log('Usage: node to-mermaid.mjs --in <architecture.json> --out <architecture.mmd> [--view overview|data|api|modules|all]')
    process.exit(args.help ? 0 : 1)
  }
  if (args.view !== 'all' && !VIEWS[args.view]) {
    console.error(`to-mermaid: неизвестный view «${args.view}» (overview|data|api|modules|all)`)
    process.exit(1)
  }
  const data = readJson(args.in)
  if (!data || !Array.isArray(data.nodes)) {
    console.error(`to-mermaid: cannot read architecture ${args.in}`)
    process.exit(1)
  }
  const outAbs = path.resolve(args.out)
  const written = []
  const writeView = (view, file) => {
    const content = VIEWS[view](data)
    fs.mkdirSync(path.dirname(file), { recursive: true })
    fs.writeFileSync(file, content)
    const lines = content.split('\n')
    written.push({ view, file, lines: lines.length, truncated: lines.some((line) => line.startsWith('%% truncated')) })
  }
  if (args.view === 'all') {
    writeView('overview', outAbs)
    const base = outAbs.replace(/\.mmd$/, '')
    for (const view of ['data', 'api', 'modules']) writeView(view, `${base}.${view}.mmd`)
  } else {
    writeView(args.view, outAbs)
  }
  for (const item of written) {
    console.log(`archmap to-mermaid: ${item.view} → ${item.file} (${item.lines} lines${item.truncated ? ', truncated' : ''})`)
  }
  console.log(`archmap to-mermaid: ${data.stats?.nodes ?? data.nodes.length} nodes / ${data.stats?.edges ?? data.edges.length} edges in source, ${written.length} file(s) written`)
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (isMain) main()
