import path from 'node:path'
import { escapeHtml, stableJson, writeText } from './lib/core.mjs'

// Accessible SVG hierarchy and adaptive visual-density rules are adapted from
// diagram-design. See assets/THIRD_PARTY_NOTICES.md.

const LAYERS = ['client', 'api', 'application', 'ai', 'event', 'data', 'infra', 'external']
const COLORS = { client: '#79a987', api: '#7f9bc2', application: '#668bb0', event: '#cf9745', ai: '#9b78ad', data: '#c58c4b', infra: '#bd6c64', external: '#8c929d' }

function architectureSvg(model) {
  const groups = new Map(); const member = new Map()
  for (const node of model.nodes.filter((item) => !['function', 'type'].includes(item.kind))) {
    const key = `${node.layer}:${node.kind}`; member.set(node.id, key)
    const current = groups.get(key) || { key, layer: node.layer, kind: node.kind, count: 0 }; current.count++; groups.set(key, current)
  }
  const active = LAYERS.filter((layer) => [...groups.values()].some((group) => group.layer === layer)); const positions = new Map(); const layerRows = new Map()
  for (const layer of active) layerRows.set(layer, [...groups.values()].filter((group) => group.layer === layer).sort((a, b) => a.kind.localeCompare(b.kind)))
  active.forEach((layer, column) => layerRows.get(layer).forEach((group, row) => positions.set(group.key, { x: 70 + column * 210, y: 90 + row * 88, w: 170, h: 58 })))
  const width = Math.max(960, active.length * 210 + 80); const height = Math.max(430, ...[...positions.values()].map((position) => position.y + position.h + 70))
  const links = new Map()
  for (const edge of model.edges) { const from = member.get(edge.from); const to = member.get(edge.to); if (!from || !to || from === to) continue; const key = `${from}->${to}:${edge.kind}`; links.set(key, { from, to, kind: edge.kind, count: (links.get(key)?.count || 0) + 1 }) }
  const zones = active.map((layer) => { const items = layerRows.get(layer); const first = positions.get(items[0].key); const maxY = Math.max(...items.map((item) => { const p = positions.get(item.key); return p.y + p.h })); return `<g class="zone"><rect x="${first.x - 15}" y="45" width="200" height="${maxY - 25}" rx="8"/><text x="${first.x}" y="69">${escapeHtml(layer.toUpperCase())}</text></g>` }).join('')
  const edges = [...links.values()].sort((a, b) => `${a.from}${a.to}${a.kind}`.localeCompare(`${b.from}${b.to}${b.kind}`)).map((edge) => { const from = positions.get(edge.from); const to = positions.get(edge.to); const forward = from.x <= to.x; const x1 = forward ? from.x + from.w : from.x; const y1 = from.y + from.h / 2; const x2 = forward ? to.x : to.x + to.w; const y2 = to.y + to.h / 2; const mid = Math.round((x1 + x2) / 2); const dashed = /publish|receive|enqueue|event|async|queue/i.test(edge.kind); return `<path class="flow${dashed ? ' async' : ''}" d="M${x1},${y1} H${mid} V${y2} H${x2}" marker-end="url(#pa-arrow)"><title>${escapeHtml(`${edge.kind} ×${edge.count}`)}</title></path>` }).join('')
  const nodes = [...groups.values()].sort((a, b) => a.key.localeCompare(b.key)).map((group) => { const p = positions.get(group.key); return `<g class="svg-node" data-layer="${escapeHtml(group.layer)}"><rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" rx="6" style="--node:${COLORS[group.layer] || COLORS.external}"/><text x="${p.x + 12}" y="${p.y + 24}">${escapeHtml(group.kind)}</text><text class="count" x="${p.x + 12}" y="${p.y + 43}">${group.count} detected</text></g>` }).join('')
  return `<svg id="overview" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="pa-title pa-desc"><title id="pa-title">Evidence-based architecture overview</title><desc id="pa-desc">Detected components grouped by architectural layer, with solid synchronous or structural connections and dashed asynchronous connections.</desc><defs><marker id="pa-arrow" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6 Z"/></marker></defs>${zones}${edges}${nodes}</svg>`
}

export function renderHtml(model, markdown, file, options = {}) {
  const data = stableJson(model).replaceAll('</script>', '<\\/script>')
  const article = escapeHtml(markdown)
    .replace(/^# (.+)$/gm, '<h1>$1</h1>').replace(/^## (.+)$/gm, '<h2>$1</h2>').replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>').replace(/^- (.+)$/gm, '<li>$1</li>').replace(/\n/g, '<br>')
  const overview = architectureSvg(model)
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Architecture - ${escapeHtml(model.repository.name)}</title>
<style>
:root{color-scheme:dark;--bg:#171a1f;--panel:#20242b;--panel2:#262b33;--muted:#a7adb8;--line:#3a414c;--text:#f1f3f5;--accent:#d88a57}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{position:sticky;top:0;z-index:2;display:flex;gap:16px;align-items:center;padding:14px 22px;background:#171a1ff2;border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}input,select{background:var(--panel);border:1px solid var(--line);color:var(--text);padding:8px 10px;border-radius:6px}.layout{display:grid;grid-template-columns:minmax(520px,1.3fr) minmax(360px,.7fr);min-height:calc(100vh - 62px)}.visual{padding:24px;border-right:1px solid var(--line);overflow:auto}#overview{display:block;min-width:900px;width:100%;height:auto;background:#1c2026;border:1px solid var(--line)}#overview .zone rect{fill:#252a31;stroke:#555d69;stroke-dasharray:4 4}#overview .zone text{fill:#a7adb8;font:600 10px ui-monospace,SFMono-Regular,monospace;letter-spacing:.12em}.flow{fill:none;stroke:#8b939f;stroke-width:1.25}.flow.async{stroke-dasharray:5 4}#pa-arrow path{fill:#8b939f}.svg-node rect{fill:#262b33;stroke:var(--node);stroke-width:1.5}.svg-node text{fill:#f1f3f5;font:600 12px ui-sans-serif,system-ui}.svg-node .count{fill:#a7adb8;font:10px ui-monospace,SFMono-Regular,monospace}#graph{padding:18px 0 0;display:grid;grid-template-columns:repeat(3,minmax(180px,1fr));gap:12px;align-content:start}.node{border:1px solid var(--line);border-left:3px solid var(--accent);background:var(--panel);border-radius:6px;padding:12px;text-align:left;color:var(--text);cursor:pointer;min-height:76px}.node:hover,.node:focus-visible{border-color:var(--accent);outline:none}.node small{display:block;color:var(--muted);margin-top:6px}.panel{padding:26px;overflow:auto;max-height:calc(100vh - 62px)}h1{font:400 30px Georgia,serif}h2{margin-top:28px;color:#e2aa82}h3{color:#c4adcf}code{background:#15181d;padding:2px 5px;border-radius:3px}blockquote{border-left:3px solid var(--accent);margin:16px 0;padding:8px 14px;background:#24282f;color:#d3d6da}table{display:block;overflow:auto;border-collapse:collapse}th,td{border:1px solid var(--line);padding:6px 9px}.badge{color:var(--muted)}#detail{padding:12px;border:1px solid var(--line);border-radius:6px;background:#191d22;margin-bottom:18px;white-space:pre-wrap}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:980px){.layout{grid-template-columns:1fr}.visual{border-right:0;border-bottom:1px solid var(--line)}}@media print{header,#graph,#detail{display:none}.layout{display:block}.visual{border:0;padding:0}.panel{max-height:none;color:#111;background:#fff}body{background:#fff}}
</style></head><body><header><strong>Principal Architecture</strong><span class="badge">${model.stats.nodes} nodes · ${model.stats.edges} edges · ${model.stats.files} files</span><input id="search" placeholder="Search nodes"><select id="layer"><option value="">All layers</option>${Object.keys(model.stats.byLayer).map((layer) => `<option>${layer}</option>`).join('')}</select></header>
<main class="layout"><section class="visual"><h1 class="sr-only">Architecture overview</h1>${overview}<section id="graph" aria-label="Detected architecture nodes"></section></section><aside class="panel"><div id="detail" role="status" aria-live="polite">Select a node to inspect its evidence.</div><article>${article}</article></aside></main>
<script type="application/json" id="model">${data}</script><script>
const model=JSON.parse(document.getElementById('model').textContent);const colors=${JSON.stringify(COLORS)};const graph=document.getElementById('graph');const search=document.getElementById('search');const layer=document.getElementById('layer');search.setAttribute('aria-label','Search architecture nodes');layer.setAttribute('aria-label','Filter architecture layer');function draw(){const q=search.value.toLowerCase();graph.innerHTML='';for(const node of model.nodes.filter(n=>(!layer.value||n.layer===layer.value)&&(!q||(n.label+' '+n.kind+' '+n.id).toLowerCase().includes(q))).slice(0,500)){const el=document.createElement('button');el.className='node';el.style='--accent:'+(colors[node.layer]||colors.external);el.innerHTML='<strong>'+escape(node.label)+'</strong><small>'+escape(node.layer+' · '+node.kind)+'</small>';el.onclick=()=>{const links=model.edges.filter(e=>e.from===node.id||e.to===node.id);document.getElementById('detail').textContent=JSON.stringify({node,relationships:links},null,2)};graph.appendChild(el)}}function escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}search.oninput=draw;layer.onchange=draw;draw();
</script></body></html>`
  writeText(path.resolve(file), html)
  return file
}
